# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "rmk-64key"
product_name = "rmk-64key"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "syjh"
chip = "nrf52840"


[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
#row2col = true
rows = 6
cols = 12
layers = 5
keymap = [
     [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backspace"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Backslash"],
        ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "WM(Enter,RShift)"],
        ["_", "LCtrl", "LGui", "LAlt", "Enter", "MO(2)", "PageUp", "PageDown", "WM(Minus,RAlt)", "WM(Equal,RCtrl)", "MO(1)", "_"],
        ["_", "_", "_", "_", "Space", "LT(1, Grave)", "LT(2, Delete)", "Space", "_", "_", "_", "_"],
    ],
]
[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "P0_13"
# numslock.low_active = false

[storage]
# Storage feature is enabled by default
# enabled = false
# !!! Warning: RMK uses last 2 sectors of your microcontroller's flash by default. You have to ensure that those flash space is not used.
# If you're using a bootloader which puts itself at the end of the flast, like Adafruit_nRF52_Bootloader, RMK will break the bootloader.
# Setting the `start_addr` manually to avoid this. See: https://haobogu.github.io/rmk/storage.html

[ble]
enabled = true


[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms" }

[[behavior.morse.morses]]
tap = "A"
hold = "WM(A, LShift)"
double_tap = "CapsLock"
hold_after_tap = "A"
timeout = "150ms"

[[behavior.morse.morses]]
tap = "Space"
hold = "LCtrl"

[[behavior.morse.morses]]
tap_actions = ["F1", "F2", "F3", "F4"]  # 1 tap = F1, 2 taps = F2, 3 taps = F3, 4 taps = F4
hold_actions = ["MO(1)", "MO(2)", "MO(3)", "MO(4)"]  # Hold after 1 tap = layer 1, etc.
timeout = "200ms"

[[behavior.morse.morses]]
tap_actions = ["Tab", "Escape", "CapsLock"]  # 1 tap = Tab, 2 taps = Escape, 3 taps = CapsLock
hold_actions = ["LCtrl", "LAlt", "LShift"]  # Hold after 1 tap = Ctrl, etc.
timeout = "250ms"



[split]
connection = "ble"


[split.central]
rows = 6
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]
[split.central.matrix]
input_pins = ["P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
output_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]


[[split.peripheral]]
rows = 6
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
[split.peripheral.matrix]
input_pins = ["P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
output_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]



